// PersonLib.CppApp.cpp : Defines the entry point for the console application.
//
// This project demonstrates consuming the DLL generated by the PersonLib project within another C++ project
//

#include "stdafx.h"
#include <iostream>

#include "PersonLib.h"

using namespace std;

int main()
{
	PersonLib::Person *p1 = new PersonLib::Person("John", 30);
	p1->SayHello();
	p1->SayAge();
	p1->AddNumbers(100, 200);
	cout << endl;

	PersonLib::Person *p2 = PersonLib::PL_C_CreatePerson("Jane", 40);
	p2->SayHello();
	p2->SayAge();
	p2->AddNumbers(500, 400);
	cout << endl;

	PersonLib::Person *p3 = PersonLib::PL_CPP_CreatePerson("Bob", 40);
	p3->SayHello();
	p3->SayAge();
	p3->AddNumbers(30, 20);
	cout << endl;

	cout << "Press Enter to exit";
	cin.ignore();
	return 0;
}
